### ISSUE TITLE
gcache无法设置默认cache的adapt

### ISSUE THREAD

**Issue by zcool321** [gogf/gcache-adapter#1]
gf版本v1.14.0
gcache-adapter版本v0.0.2

由于默认Cache对象是私有的，无法设置adapt，代码如下

```go
package gcache

// Default cache object.
var defaultCache = New()
```

期望：
如gcache.Set可以通过adapt默认使用redis,加入gcache.setAdapt

**Comment by gqcn** [comment]
@zcool321 是的，全局的那个包私有对象是没办法改的，因为全局包方法只能是内存缓存。
